---
branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: bundle exec rake spec SPEC_OPTS='--format documentation'
env:
  matrix:
    - PUPPET_VERSION="2.7.23"
    - PUPPET_VERSION="3.0.2"
    - PUPPET_VERSION="3.1.1"
    - PUPPET_VERSION="3.2.4"
    - PUPPET_VERSION="3.3.1"
notifications:
  email:
    - justin@downing.us
